apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: |
    <source>
      @type tail
      format none
      path /var/log/messages.log
      pos_file /var/log/messages.log.pos
      tag app
    </source>

    <filter app>
      @type grep
        exclude1 message filtered
    </filter>

    <match app>
      @type stdout
    </match>
