kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.StorageClass.name }}
  resources:
    requests:
      storage: 1Gi
