apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  labels:
{{ toYaml .Values.label | indent 4 }}
spec:
  containers:
  - name: {{ .Values.pod.containerName }}
    image: {{ .Values.pod.image }}:{{ .Values.pod.tag }}
    ports:
    - containerPort: 8080
    env:
    - name: RESPONSE
      value: {{ .Values.pod.response }}
    volumeMounts:
    - name: {{ .Values.volumes.logs.name }}
      mountPath: "/opt/app-volume"
  - name: {{ .Values.sidecar_in_pod.name }}
    env:
    - name: FLUENTD_CONF
      value: /opt/fluentd/fluentd.conf
    image: {{ .Values.sidecar_in_pod.image }}:{{ .Values.sidecar_in_pod.tag }}
    volumeMounts:
    - name: {{ .Values.volumes.logs.name }}
      mountPath: /var/log
    - name: {{ .Values.volumes.fluentd.name }}
      mountPath: "/opt/fluentd"
  volumes:
    - name: {{ .Values.volumes.logs.name }}
      persistentVolumeClaim:
        claimName: {{ .Values.persistentVolumeClaim.name }}
    - name: {{ .Values.volumes.fluentd.name }}
      configMap:
        name: {{ .Values.configMap.name }}
