apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.name }}
spec:
  type: ClusterIP
  selector:
{{ toYaml .Values.label | indent 4 }}
  ports:
    - protocol: TCP
      targetPort: 8080
      port: {{ .Values.services.port }}
